version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      - image: centos/centos7
    steps:
      - checkout
      - run:
          name: "setup"
          command: |
            ls
            ./setup.sh
      - run:
          name: "uninstall"
          command: |
            yes
            ./setup.sh -u