# .circleci/config.yml
version: 2
jobs:
  run-setup-uninstall:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run:
          name: run setup
          command: |
            ls
            ./setup.sh
      - run: 
          name: run uninstall
          command: |
            yes
            ./setup.sh -u

workflows:
  version: 2
  run-setup-uninstall:
    jobs:
      - run-setup-uninstall
